name: "veritool"
description: "Veritool is a minimalistic Dart CLI for Semantic Versioning-based version number updates in Flutter app&#x27;s pubspec.yaml file."
version: "0.1.0+16"
homepage: "https://github.com/sheeroo/veritool/blob/main/README.md"
repository: "https://github.com/sheeroo/veritool"
environment: 
  sdk: ">=2.18.0 <4.0.0"

dependencies: 
  args: "^2.4.0"
  cli_completion: "^0.5.1"
  mason_logger: "^0.3.2"
  pub_semver: "^2.1.3"
  pub_updater: "^0.5.0"
  yaml: "^3.1.1"

dev_dependencies: 
  build_runner: "^2.0.0"
  build_verify: "^3.0.0"
  build_version: "^2.0.0"
  mocktail: "^1.0.4"
  test: "^1.19.2"
  very_good_analysis: "^7.0.0"

executables: 
  veritool: null